### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by Kampii** [6/realtime-fabric#1]
Hi,

I have uploaded all the files on my server, however, I have a trouble launching the html page. How should it be set up?

Best

**Comment by 6** [comment]
Hi @Kampii, I haven't updated this repo in 4 years, and the meteor project which it depends on has probably changed significantly.

I don't have any plans currently to update it to work with the newest meteor version, but you could look at the docs here https://www.meteor.com/ to see if you could figure it out.

Also, I see someone has a fork which was updated more recently: https://github.com/bobbigmac/realtime-fabric - that may work better

**Comment by Kampii** [comment]
Thank you for your reply. I will check that!
